ExpTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from income.views import income_view
from expense.views import index_view, category_view

urlpatterns = [
    path('', index_view),
    path('addIncome/', income_view, name='addIncomeView'),
    path('addCategory/', category_view, name='category_view'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

expense/models.py
from django.db import models

# Create your models here.

class ExpenseCategory(models.Model):
    name = models.CharField(max_length=20)
    monthlyLimit = models.FloatField()

income/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class Income(models.Model):

    cat = (('salary', 'Salary'),
              ('bonus', 'Bonus'),
              ('something else', 'Something else'))       
    income = models.FloatField()
    date = models.DateField(default=datetime.now)
    category = models.CharField(max_length=7, choices=cat, default='Salary')
    biweekly = models.BooleanField(default=True)
    comments = models.TextField(blank=True, null=True)
    

expense/forms.py
from django.forms import ModelForm
from .models import ExpenseCategory

class AddCategory(ModelForm):
    class Meta:
        model = ExpenseCategory
        fields = ['name', 'monthlyLimit'] 

income/forms.py
from django.forms import ModelForm
from django.forms.widgets import SelectDateWidget, Textarea
from .models import Income



class AddIncome(ModelForm):
    class Meta:
        model = Income
        fields = ['income', 'date', 'category', 'biweekly', 'comments'] 
        widgets = {
            'date': SelectDateWidget(),
            'comments':Textarea(attrs={'rows':3, 'cols':30}),
            }

expense/views.py
from django.shortcuts import render
from .forms import AddCategory

# Create your views here.
def index_view(request, *args, **kwargs):
    
    return render(request, "index.html", {})


def category_view(request, *args, **kwargs):
    if request.method == "POST":
        form = AddCategory(request.POST)
        if form.is_valid():
            income = form.save(commit=False)
            income.save()
            form = AddCategory()
    else:
        form = AddCategory()
    return render(request, "addCategory.html", {'form':form})

income/views.py
from django.shortcuts import render
from .forms import AddIncome

# Create your views here.

def income_view(request, *args, **kwargs):
    if request.method == "POST":
        form = AddIncome(request.POST)
        if form.is_valid():
            income = form.save(commit=False)
            income.save()
            form = AddIncome()
    else:
        form = AddIncome()
    return render(request, "addIncome.html", {'form':form})

templates/addCategory.html
{% extends 'base.html' %}

 

{% block content %}
    
    <div class="container-fluid  bg-light text-dark">
           
                    <h5>Enter Category:</h5>
                    
                   <p></p>
    <form method="POST">{% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group row">
            {{ form.income.errors }}
            <label for="id_income" class="col-sm-2">Category Name</label>
            <div class="col-sm-10">{{ form.name }}</div>
        </div>  
        <div class="form-group row">
            {{ form.date.errors }}
            <label for="id_date" class="col-sm-2 col-form-label">Montly Limit</label>
        <div class="col-sm-10">
            {{ form.monthlyLimit }}</div>
        
        </div>
            
        <button type="submit" id="btnShow" class="btn btn-outline-primary">Save Me</button>
    </form>


   
</div>

    

{% endblock %}

templates/addIncome.html
{% extends 'base.html' %}

 

{% block content %}
    
    <div class="container-fluid  bg-light text-dark">
           
                    <h5>Enter Income:</h5>
                    
                   <p></p>
    <form method="POST">{% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group row">
            {{ form.income.errors }}
            <label for="id_income" class="col-sm-2">Income</label>
            <div class="col-sm-10">{{ form.income }}</div>
        </div>  
        <div class="form-group row">
            {{ form.date.errors }}
            <label for="id_date" class="col-sm-2 col-form-label">Date</label>
        <div class="col-sm-10">
            {{ form.date }}</div>
        
        </div>
        <div class="form-group row">
            {{ form.category.errors }}
            <label for="id_category" class="col-sm-2 col-form-label">Category</label>
            <div class="col-sm-10">{{ form.category }}</div>
        </div>
        <div class="form-group row">
            {{ form.biweekly.errors }}
            <label for="id_biweekly" class="col-sm-2 col-form-label">Biweekly</label>
            <div class="col-sm-10">{{ form.biweekly }}</div>
        </div>
        <div class="form-group row">
                {{ form.comments.errors }}
                <label for="id_comments" class="col-sm-2 col-form-label">Comments</label>
                <div class="col-sm-10">{{ form.comments }}</div>
            </div>
            
        <button type="submit" id="btnShow" class="btn btn-outline-primary">Save Me</button>
    </form>


   
</div>

    

{% endblock %}

templates/base.html
{# Load the tag library #}
{% load bootstrap4 %}



{# Load CSS and JavaScript #}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Expense Tracker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/addIncome">Income</a>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Expense
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/addCategory">Add Expense Category</a>
            <a class="dropdown-item" href="#">Add Expense</a>
          </div>
        </li>

      </ul>
    </div>
</nav>
{% block content %}
{% endblock %}
  

templates/index.html
{% extends 'base.html' %}

{% block content %}

<p>Welcome {{request.user}}</p>

{% endblock %}